name: Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != ''
      && contains(github.event.comment.body, '/rebase')
      && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')

    steps:
      - uses: actions/checkout@v3

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
